import { Card } from '@/components/ui/card';
import { Lightbulb, ArrowRight } from 'lucide-react';

export default function ManagerInsightsPanel({ insights, onActionClick }) {
  if (!insights || insights.length === 0) return null;

  return (
    <Card className="border-border bg-gradient-to-br from-surface to-card relative overflow-hidden group p-1">
      {/* Decorative accent pulse */}
      <div className="absolute top-0 right-0 w-48 h-48 bg-purple-500/10 rounded-full blur-3xl -mr-16 -mt-16 pointer-events-none" />
      <div className="absolute bottom-0 left-0 w-48 h-48 bg-blue-500/10 rounded-full blur-3xl -ml-24 -mb-24 pointer-events-none" />

      <div className="bg-card rounded-lg relative z-10 p-5 h-full flex flex-col">
        <div className="flex items-center gap-2 mb-4">
          <div className="p-1.5 rounded-md bg-purple-500/10 text-purple-400">
            <Lightbulb className="w-4 h-4" />
          </div>
          <h3 className="text-sm font-semibold tracking-wide uppercase text-foreground">AI Manager Insights</h3>
        </div>

        <div className="space-y-4 flex-1">
          {insights.map((insight, idx) => (
            <div key={idx} className="relative pl-4 border-l-2 border-primary/30 py-1 hover:border-primary transition-colors">
              <p className="text-sm leading-relaxed text-foreground/90">
                {insight.text}
              </p>
              {insight.actionable && onActionClick && (
                <button 
                  onClick={() => onActionClick(insight)}
                  className="mt-2 text-xs font-semibold text-primary flex items-center gap-1 hover:text-primary/80 transition-colors"
                >
                  {insight.actionText || 'Take Action'} <ArrowRight className="w-3 h-3" />
                </button>
              )}
            </div>
          ))}
        </div>

        <div className="mt-6 pt-4 border-t border-border/50 flex justify-between items-center text-[10px] uppercase font-bold tracking-wider text-muted-foreground/50">
          <span>Generated by OrgOS AI</span>
          <span>Kinetic Engine v2</span>
        </div>
      </div>
    </Card>
  );
}
